services:
  servidor:
    build: .
    container_name: servidor-tcp-udp
    command: python -m src.servidor.servidor
    ports:
      # O Docker mapeia apenas TCP por padrão. Explicitar o UDP é crucial aqui!
      - "5555:5555/tcp"
      - "5555:5555/udp"
    networks:
      - rede-comunicacao
    restart: unless-stopped

  # Template preparado para rodar clientes normais (iterativos)
  cliente-tcp:
    build: .
    stdin_open: true # Mantém a entrada padrão aberta para você digitar o username
    tty: true # Simula um terminal
    command: python -m src.cliente.cliente_tcp
    networks:
      - rede-comunicacao
    environment:
      - ALVO_IP=servidor
      - ALVO_PORTA=5555

  cliente-udp:
    build: .
    command: python -m src.cliente.cliente_udp
    stdin_open: true # Mantém a entrada padrão aberta para você digitar o username
    tty: true # Simula um terminal
    networks:
      - rede-comunicacao
    environment:
      - ALVO_IP=servidor
      - ALVO_PORTA=5555

  teste-estresse-tcp:
    build: .
    command: python tests/teste_estresse.py
    stdin_open: true
    tty: true
    depends_on:
      - servidor
    networks:
      - rede-comunicacao
    environment:
      - ALVO_IP=servidor
      - ALVO_PORTA=5555

  teste-estresse-udp:
    build: .
    command: python tests/teste_estresse_udp.py
    stdin_open: true
    tty: true
    depends_on:
      - servidor
    networks:
      - rede-comunicacao
    environment:
      - ALVO_IP=servidor
      - ALVO_PORTA=5555

networks:
  rede-comunicacao:
    driver: bridge
